/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable_1.h"
#include "Pin_SW1.h"
#include "Pin_SW1_aliases.h"
#include "isr_1.h"
#include "ADC_SAR_Seq_1.h"
#include "Pin_TC1_Red.h"
#include "Pin_TC1_Red_aliases.h"
#include "Pin_TC_Blue_1k.h"
#include "Pin_TC_Blue_1k_aliases.h"
#include "Thermocouple_1.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "Opamp_1.h"
#include "Pin_Opamp_1_Out.h"
#include "Pin_Opamp_1_Out_aliases.h"
#include "Pin_ADC_Vref.h"
#include "Pin_ADC_Vref_aliases.h"
#include "AMux_1.h"
#include "Pin_TC2_Red.h"
#include "Pin_TC2_Red_aliases.h"
#include "Pin_TC3_Red.h"
#include "Pin_TC3_Red_aliases.h"
#include "Pin_Relays.h"
#include "Pin_Relays_aliases.h"
#include "Pin_Builtin_LED.h"
#include "Pin_Builtin_LED_aliases.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

